[Service]
ExecStart=
ExecStart=/usr/bin/python3 /usr/local/lib/virp/demo/network.py --management-interface eth0 --container-bridge br-demo --dns 10.0.20.1 --dns 1.1.1.1 --ntp 10.0.20.1 --demo-witness-ssh --demo-caddy-uid 995 --apply
