#!/usr/bin/env python3
"""
v3 (Ed25519) observation signing — end-to-end through the SHIPPED binaries.

Nothing here props a guard up by hand. The daemon is the real
build/virp-onode-prod; the key is generated by the real
`virp-tool keygen obskey`; the daemon loads it through its own -O path
and custody gate; the verifier is `virp-tool obs-verify`, which takes
ONLY the public key (a 64-byte secret is refused by that command).

Cases:
  A. daemon -O <key>: session handshake, execute obs_version 3 → byte 0
     is 3, obs-verify(PUBLIC KEY ONLY) says VALID; tamper one byte of
     header / payload / HMAC → all three INVALID; v1 request on the
     same daemon still returns a v1 body.
  B. daemon WITHOUT -O: startup stderr carries the loud UNAVAILABLE line
     exactly once; obs_version 3 → 4-byte VIRP_ERR_KEY_NOT_LOADED, not a
     downgraded body; v1 and v2 unchanged.
  C. daemon -O <key with mode 0644>: refuses to start (FATAL).
  D. daemon -O <missing file>: refuses to start (FATAL).

Skips (does not pass) when the binaries are absent. Run via
`make test-obs-v3-e2e`, which builds them first.
"""

import json
import os
import socket
import stat
import struct
import subprocess
import sys
import tempfile
import time
import unittest

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
ONODE_BIN = os.environ.get("VIRP_ONODE_BIN",
                           os.path.join(REPO_ROOT, "build", "virp-onode-prod"))
TOOL_BIN = os.environ.get("VIRP_TOOL_BIN",
                          os.path.join(REPO_ROOT, "build", "virp-tool"))

VIRP_FRAME_VERSION = 0x02
VIRP_VERSION_1 = 1
VIRP_VERSION_2 = 2
VIRP_VERSION_3 = 3
VIRP_ERR_KEY_NOT_LOADED = -14        # include/virp.h
VIRP_ERR_SESSION_INVALID = -30
OBS_V2_HEADER = 88
HMAC_LEN = 32
ED25519_SIG_LEN = 64
UNAVAILABLE_MARK = "OBSERVATION SIGNING UNAVAILABLE"


def _send_framed(sock, obj):
    payload = json.dumps(obj).encode("utf-8")
    sock.sendall(struct.pack("!I", 1 + len(payload)) +
                 bytes([VIRP_FRAME_VERSION]) + payload)


def _recv_exact(sock, n):
    buf = b""
    while len(buf) < n:
        chunk = sock.recv(n - len(buf))
        if not chunk:
            raise ConnectionError("socket closed prematurely")
        buf += chunk
    return buf


def _recv_framed(sock):
    length = struct.unpack("!I", _recv_exact(sock, 4))[0]
    return b"" if length == 0 else _recv_exact(sock, length)


def _request(sock_path, obj):
    s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    s.settimeout(10.0)
    try:
        s.connect(sock_path)
        _send_framed(s, obj)
        return _recv_framed(s)
    finally:
        s.close()


def _as_error(resp):
    """A 4-byte response is a typed error (big-endian int32)."""
    if len(resp) != 4:
        return None
    return struct.unpack("!i", resp)[0]


def _handshake(sock_path, client_id):
    """SESSION_HELLO → SESSION_BIND, the same JSON flow test_onode.c uses."""
    ack = json.loads(_request(sock_path, {
        "action": "session_hello", "client_id": client_id,
        "client_nonce": "0011223344556677"}))
    bound = json.loads(_request(sock_path, {
        "action": "session_bind", "client_id": client_id,
        "session_id": ack["session_id"],
        "client_nonce": ack["client_nonce"],
        "server_nonce": ack["server_nonce"]}))
    return bound


class _Daemon:
    """A real virp-onode-prod subprocess with a mock device."""

    def __init__(self, tmp, tag, obskey_path=None):
        self.tmp = tmp
        self.sock_path = os.path.join(tmp, f"onode-{tag}.sock")
        self.stderr_path = os.path.join(tmp, f"stderr-{tag}.log")
        self.okey_path = os.path.join(tmp, f"okey-{tag}.bin")
        with open(self.okey_path, "wb") as f:
            f.write(os.urandom(32))
        os.chmod(self.okey_path, 0o600)
        devices = os.path.join(tmp, f"devices-{tag}.json")
        with open(devices, "w") as f:
            json.dump({"devices": [{
                "hostname": "R6", "host": "127.0.0.1", "port": 22,
                "vendor": "mock", "username": "u", "password": "p",
                "node_id": "06060606"}]}, f)
        argv = [ONODE_BIN, "-k", self.okey_path, "-s", self.sock_path,
                "-d", devices, "-n", "00000001"]
        if obskey_path:
            argv += ["-O", obskey_path]
        self.stderr_f = open(self.stderr_path, "wb")
        self.proc = subprocess.Popen(argv, stdout=subprocess.DEVNULL,
                                     stderr=self.stderr_f)

    def wait_ready(self, timeout=5.0):
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            if self.proc.poll() is not None:
                return False
            if os.path.exists(self.sock_path):
                try:
                    probe = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
                    probe.settimeout(0.5)
                    probe.connect(self.sock_path)
                    probe.close()
                    return True
                except OSError:
                    pass
            time.sleep(0.05)
        return False

    def wait_exit(self, timeout=5.0):
        try:
            return self.proc.wait(timeout=timeout)
        except subprocess.TimeoutExpired:
            return None

    def stderr(self):
        self.stderr_f.flush()
        with open(self.stderr_path, "rb") as f:
            return f.read().decode("utf-8", errors="replace")

    def stop(self):
        if self.proc.poll() is None:
            self.proc.terminate()
            try:
                self.proc.wait(timeout=5.0)
            except subprocess.TimeoutExpired:
                self.proc.kill()
                self.proc.wait()
        self.stderr_f.close()


class ObsV3E2E(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        for b in (ONODE_BIN, TOOL_BIN):
            if not os.path.exists(b):
                raise unittest.SkipTest(f"missing {b}; run: make test-obs-v3-e2e")
        cls.tmp = tempfile.mkdtemp(prefix="virp_test_v3e2e_")
        cls.prefix = os.path.join(cls.tmp, "obs")
        # The REAL keygen — not a keypair minted in this process.
        r = subprocess.run([TOOL_BIN, "keygen", "obskey", cls.prefix],
                           capture_output=True, text=True)
        if r.returncode != 0:
            raise RuntimeError(f"virp-tool keygen obskey failed: {r.stderr}")
        cls.sk_path = cls.prefix + ".key"
        cls.pk_path = cls.prefix + ".pub"

    @classmethod
    def tearDownClass(cls):
        # Leave nothing secret behind.
        for n in os.listdir(cls.tmp):
            try:
                os.unlink(os.path.join(cls.tmp, n))
            except OSError:
                pass
        try:
            os.rmdir(cls.tmp)
        except OSError:
            pass

    # -- custody of the generated files --------------------------------
    def test_00_keygen_writes_0600_secret_and_0644_public(self):
        st = os.stat(self.sk_path)
        self.assertEqual(stat.S_IMODE(st.st_mode), 0o600)
        self.assertEqual(st.st_size, 64)
        st = os.stat(self.pk_path)
        self.assertEqual(stat.S_IMODE(st.st_mode), 0o644)
        self.assertEqual(st.st_size, 32)

    # -- A: the real path -----------------------------------------------
    def test_A_daemon_with_obskey_emits_v3_that_public_key_verifies(self):
        d = _Daemon(self.tmp, "A", obskey_path=self.sk_path)
        try:
            self.assertTrue(d.wait_ready(), f"daemon died:\n{d.stderr()}")
            err = d.stderr()
            self.assertIn("Loaded Ed25519 observation-signing key", err)
            self.assertNotIn(UNAVAILABLE_MARK, err)

            # v3 needs a session (its HMAC trailer is session-keyed);
            # without one the request must fail, not fall back.
            resp = _request(d.sock_path, {"action": "execute", "device": "R6",
                                          "command": "show ip route",
                                          "obs_version": 3})
            self.assertEqual(_as_error(resp), VIRP_ERR_SESSION_INVALID)

            bound = _handshake(d.sock_path, "v3-e2e")
            self.assertIn("bound", json.dumps(bound), bound)

            obs = _request(d.sock_path, {"action": "execute", "device": "R6",
                                         "command": "show ip route",
                                         "obs_version": 3})
            self.assertIsNone(_as_error(obs), f"typed error {_as_error(obs)}")
            self.assertGreaterEqual(len(obs),
                                    OBS_V2_HEADER + HMAC_LEN + ED25519_SIG_LEN)
            self.assertEqual(obs[0], VIRP_VERSION_3)
            payload_len = struct.unpack("!I", obs[84:88])[0]
            self.assertEqual(len(obs),
                             OBS_V2_HEADER + payload_len + HMAC_LEN + ED25519_SIG_LEN)
            self.assertIn(b"6.6.6.6", obs[OBS_V2_HEADER:OBS_V2_HEADER + payload_len])

            # PUBLIC-KEY-ONLY verification by the shipped tool.
            obs_path = os.path.join(self.tmp, "obs-good.bin")
            with open(obs_path, "wb") as f:
                f.write(obs)
            r = subprocess.run([TOOL_BIN, "obs-verify", self.pk_path, obs_path],
                               capture_output=True, text=True)
            self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
            self.assertIn("VALID (Ed25519, public-key-only verification)", r.stdout)

            # obs-verify REFUSES the secret key: the verifier cannot be
            # handed forge-capable material even by mistake.
            r = subprocess.run([TOOL_BIN, "obs-verify", self.sk_path, obs_path],
                               capture_output=True, text=True)
            self.assertNotEqual(r.returncode, 0)
            self.assertIn("obs-verify takes no secrets", r.stderr)

            # Tamper exactly one byte in each covered region.
            hmac_off = OBS_V2_HEADER + payload_len
            for label, off in (("header(timestamp)", 16),
                               ("payload", OBS_V2_HEADER),
                               ("hmac", hmac_off)):
                bad = bytearray(obs)
                bad[off] ^= 0x01
                bad_path = os.path.join(self.tmp, f"obs-bad-{label}.bin")
                with open(bad_path, "wb") as f:
                    f.write(bytes(bad))
                r = subprocess.run([TOOL_BIN, "obs-verify", self.pk_path, bad_path],
                                   capture_output=True, text=True)
                self.assertNotEqual(r.returncode, 0, label)
                self.assertIn("INVALID", r.stdout, label)

            # v1 on the same daemon is untouched by the loaded key.
            v1 = _request(d.sock_path, {"action": "execute", "device": "R6",
                                        "command": "show ip route"})
            self.assertIsNone(_as_error(v1))
            self.assertEqual(v1[0], VIRP_VERSION_1)
            # v2 on the same daemon is untouched too.
            v2 = _request(d.sock_path, {"action": "execute", "device": "R6",
                                        "command": "show ip route",
                                        "obs_version": 2})
            self.assertIsNone(_as_error(v2))
            self.assertEqual(v2[0], VIRP_VERSION_2)
            self.assertEqual(len(v2), OBS_V2_HEADER +
                             struct.unpack("!I", v2[84:88])[0] + HMAC_LEN)
            _request(d.sock_path, {"action": "session_close"})
        finally:
            d.stop()

    # -- B: fallback ------------------------------------------------------
    def test_B_daemon_without_obskey_refuses_v3_and_keeps_v1_v2(self):
        d = _Daemon(self.tmp, "B")
        try:
            self.assertTrue(d.wait_ready(), f"daemon died:\n{d.stderr()}")
            err = d.stderr()
            self.assertEqual(err.count(UNAVAILABLE_MARK), 1, err)
            self.assertIn("never downgraded", err)

            bound = _handshake(d.sock_path, "v3-e2e-nokey")
            self.assertIn("bound", json.dumps(bound), bound)

            resp = _request(d.sock_path, {"action": "execute", "device": "R6",
                                          "command": "show ip route",
                                          "obs_version": 3})
            self.assertEqual(_as_error(resp), VIRP_ERR_KEY_NOT_LOADED,
                             "v3 without a key must be a typed refusal, "
                             f"got {len(resp)} bytes")

            v2 = _request(d.sock_path, {"action": "execute", "device": "R6",
                                        "command": "show ip route",
                                        "obs_version": 2})
            self.assertIsNone(_as_error(v2))
            self.assertEqual(v2[0], VIRP_VERSION_2)
            v1 = _request(d.sock_path, {"action": "execute", "device": "R6",
                                        "command": "show ip route"})
            self.assertIsNone(_as_error(v1))
            self.assertEqual(v1[0], VIRP_VERSION_1)
            _request(d.sock_path, {"action": "session_close"})
        finally:
            d.stop()

    # -- C/D: configured-but-unloadable is FATAL --------------------------
    def test_C_insecure_mode_obskey_is_fatal(self):
        lax = os.path.join(self.tmp, "obs-lax.key")
        with open(self.sk_path, "rb") as f:
            data = f.read()
        with open(lax, "wb") as f:
            f.write(data)
        os.chmod(lax, 0o644)
        d = _Daemon(self.tmp, "C", obskey_path=lax)
        try:
            rc = d.wait_exit()
            self.assertIsNotNone(rc, "daemon kept running with a 0644 obskey")
            self.assertNotEqual(rc, 0)
            err = d.stderr()
            self.assertIn("insecure mode", err)
            self.assertIn("FATAL", err)
            self.assertFalse(os.path.exists(d.sock_path))
        finally:
            d.stop()
            os.unlink(lax)

    def test_D_missing_obskey_is_fatal(self):
        d = _Daemon(self.tmp, "D",
                    obskey_path=os.path.join(self.tmp, "does-not-exist.key"))
        try:
            rc = d.wait_exit()
            self.assertIsNotNone(rc)
            self.assertNotEqual(rc, 0)
            self.assertIn("FATAL", d.stderr())
        finally:
            d.stop()


if __name__ == "__main__":
    unittest.main(verbosity=2)
