#!/bin/sh
# Generate the build-id translation unit.
#
# WHY THIS EXISTS: v0.2.0 shipped reporting build_id="unknown" in its
# node_config entry. The cause was not a missing value — it was that
# -DVIRP_BUILD_ID was placed on the virp_onode_prod.c compile line only,
# while the code that USES it (virp_onode.c) is compiled into libvirp.a
# without the define. The macro therefore never reached the code, and the
# "unknown" fallback won silently. A define on the wrong translation unit
# is invisible; a generated translation unit that every consumer links is
# not.
#
# Resolution order:
#   1. git describe --always --dirty   (the real provenance, incl. -dirty)
#   2. $VIRP_BUILD_ID                  (git unavailable: tarball builds)
#   3. FAIL                            (a build with no provenance is not
#                                       a build we are willing to ship)
#
# Usage: gen-build-id.sh <output.c>
set -eu

out="${1:?usage: gen-build-id.sh <output.c>}"

id=""
if id_git=$(git describe --always --dirty 2>/dev/null) && [ -n "$id_git" ]; then
    id="$id_git"
    src="git describe"
elif [ -n "${VIRP_BUILD_ID:-}" ]; then
    id="$VIRP_BUILD_ID"
    src="VIRP_BUILD_ID environment"
else
    echo "FAIL: cannot determine a build id." >&2
    echo "  'git describe --always --dirty' produced nothing (no git, or no repo)," >&2
    echo "  and VIRP_BUILD_ID is unset. Refusing to build a binary that would" >&2
    echo "  report its own provenance as unknown — that is the v0.2.0 defect." >&2
    echo "  Set VIRP_BUILD_ID=<id> to build outside a git worktree." >&2
    exit 1
fi

# The id lands in a C string literal and in a JSON chain entry. Refuse
# anything that could break out of either rather than escaping it.
case "$id" in
    *[!A-Za-z0-9._/+-]*)
        echo "FAIL: build id '$id' contains characters outside [A-Za-z0-9._/+-]" >&2
        exit 1 ;;
esac

tmp="$out.tmp.$$"
cat > "$tmp" <<CEOF
/* GENERATED by scripts/gen-build-id.sh — do not edit, do not commit.
 * Source: $src */
const char *virp_build_id(void);
const char *virp_build_id(void) { return "$id"; }
CEOF

# Only touch the output when the value actually changed, so an unchanged
# build id does not force a relink of everything on every make.
if [ -f "$out" ] && cmp -s "$tmp" "$out"; then
    rm -f "$tmp"
else
    mv -f "$tmp" "$out"
fi
