/*
 * Copyright (c) 2026 Third Level IT LLC. All rights reserved.
 * VIRP — Verified Infrastructure Response Protocol
 * Session state management (RFC Section 4)
 *
 * In-memory only — no SQLite persistence.
 * Single active session enforced (reject new HELLO if session ACTIVE).
 * If O-Node restarts, client must re-handshake.
 */

#ifndef VIRP_SESSION_H
#define VIRP_SESSION_H

#include <stdint.h>
#include <stddef.h>
#include "virp.h"

/* How long to wait for SESSION_BIND after HELLO_ACK before resetting */
#define VIRP_SESSION_BIND_TIMEOUT_NS   (30ULL * 1000000000ULL)  /* 30 seconds */

/* How long an ACTIVE session can be idle before forced reset */
#define VIRP_SESSION_IDLE_TIMEOUT_NS   (300ULL * 1000000000ULL) /* 5 minutes */

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Forward declaration of virp_context_t. Full definition lives in
 * virp_context.h, which callers of the threaded API must include.
 * Using a forward decl here keeps virp_session.h / virp_context.h
 * free of a circular include.
 */
typedef struct virp_context_s virp_context_t;

typedef enum {
    VIRP_SESSION_DISCONNECTED = 0,
    VIRP_SESSION_HELLO_SENT   = 1,  /* client sent HELLO, awaiting ACK */
    VIRP_SESSION_NEGOTIATED   = 2,  /* O-Node sent HELLO_ACK */
    VIRP_SESSION_BOUND        = 3,  /* SESSION_BIND confirmed */
    VIRP_SESSION_ACTIVE       = 4,  /* observation/intent exchange allowed */
    VIRP_SESSION_CLOSED       = 5,
} virp_session_state_t;

typedef struct {
    virp_session_state_t state;

    uint8_t  session_id[16];     /* generated by O-Node at HELLO_ACK */
    uint8_t  client_nonce[8];    /* from client HELLO */
    uint8_t  server_nonce[8];    /* generated by O-Node */

    uint8_t  selected_version;   /* negotiated version */
    uint8_t  selected_algorithm; /* 0x01 = HMAC-SHA256 */

    char     client_id[64];      /* from HELLO */
    char     server_id[64];      /* this O-Node's identity */

    uint64_t established_at_ns;  /* timestamp when ACTIVE was entered */
    uint64_t last_seq;           /* last observation seq_num in this session */

    uint64_t hello_ack_sent_at_ns; /* when NEGOTIATED was entered */
    uint64_t last_activity_ns;     /* updated on every signed observation */
    uint64_t generation;           /* incremented on every reset, never decremented */

    uint8_t  session_key[32];       /* HKDF-derived, valid only when ACTIVE  */
    uint8_t  transcript_hash[32];   /* SHA-256(HELLO||HELLO_ACK||SESSION_BIND) */
    int      session_key_valid;     /* 1 if session_key is ready to use       */

    /* Transcript buffer — accumulates serialized handshake messages */
    uint8_t  transcript_buf[2048];
    size_t   transcript_len;
} virp_session_t;

/*
 * Session API
 *
 * Every function takes a virp_context_t *ctx as its first parameter.
 * Callers allocate contexts with virp_context_new() (see
 * virp_context.h) and release them with virp_context_destroy();
 * session material is wiped as part of context destruction.
 */
virp_error_t virp_session_init(virp_context_t *ctx, const char *server_id);
void virp_session_reset(virp_context_t *ctx);
virp_session_state_t virp_session_state(virp_context_t *ctx);

/* Returns VIRP_OK if session is ACTIVE and ready for observations */
virp_error_t virp_session_require_active(virp_context_t *ctx);

/*
 * Check for session timeouts. Call from O-Node main loop or before
 * processing any message. Forces reset if NEGOTIATED waited too long
 * for SESSION_BIND, or ACTIVE session has been idle too long.
 * Returns VIRP_ERR_SESSION_INVALID if a timeout was enforced.
 */
virp_error_t virp_session_check_timeouts(virp_context_t *ctx);

/*
 * Call immediately when the transport socket closes or errors.
 * Forces unambiguous transition to DISCONNECTED regardless of state.
 */
void virp_session_on_disconnect(virp_context_t *ctx);

/*
 * Wipe all session material (keys, nonces, transcript).
 * Call at process exit or from an atexit handler.
 */
void virp_session_destroy(virp_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* VIRP_SESSION_H */
