"""
Auto-generated from include/virp.h by scripts/gen_constants.py.
Do not edit by hand.
"""

VIRP_VERSION = 1
VIRP_VERSION_2 = 2
VIRP_HEADER_SIZE = 56
VIRP_HMAC_SIZE = 32
VIRP_KEY_SIZE = 32
VIRP_MAX_MESSAGE_SIZE = 65536
VIRP_MAX_PAYLOAD_SIZE = (VIRP_MAX_MESSAGE_SIZE - VIRP_HEADER_SIZE)
VIRP_CHANNEL_OC = 0x01
VIRP_CHANNEL_OBS = VIRP_CHANNEL_OC
VIRP_CHANNEL_IC = 0x02
VIRP_CHANNEL_INTENT = VIRP_CHANNEL_IC
VIRP_TIER_GREEN = 0x01
VIRP_TIER_YELLOW = 0x02
VIRP_TIER_RED = 0x03
VIRP_TIER_BLACK = 0xFF
VIRP_MSG_OBSERVATION = 0x01
VIRP_MSG_HELLO = 0x02
VIRP_MSG_PROPOSAL = 0x10
VIRP_MSG_APPROVAL = 0x11
VIRP_MSG_INTENT_ADV = 0x20
VIRP_MSG_INTENT_WD = 0x21
VIRP_MSG_HEARTBEAT = 0x30
VIRP_MSG_TEARDOWN = 0xF0
VIRP_MSG_SESSION_HELLO = 0x40
VIRP_MSG_SESSION_HELLO_ACK = 0x41
VIRP_MSG_SESSION_BIND = 0x42
VIRP_MSG_SESSION_CLOSE = 0x43
VIRP_MSG_SESSION_ERROR = 0x4F
VIRP_OBS_PREFIX_REACHABLE = 0x01
VIRP_OBS_LINK_STATE = 0x02
VIRP_OBS_PEER_STATE = 0x03
VIRP_OBS_FORWARDING_STATE = 0x04
VIRP_OBS_RESOURCE_STATE = 0x05
VIRP_OBS_SECURITY_STATE = 0x06
VIRP_OBS_DEVICE_OUTPUT = 0x07
VIRP_OBS_INTENT_SIGNED = 0x08
VIRP_OBS_OUTCOME_SIGNED = 0x09
VIRP_OBS_CHAIN_ENTRY = 0x0A
VIRP_OBS_CHAIN_VERIFY = 0x0B
VIRP_OBS_INTENT_STORED = 0x0C
VIRP_OBS_INTENT_FETCHED = 0x0D
VIRP_OBS_INTENT_EXECUTED = 0x0E
VIRP_SCOPE_LOCAL = 0x01
VIRP_SCOPE_ADJACENT = 0x02
VIRP_SCOPE_MEASURED = 0x03
VIRP_APPROVAL_APPROVE = 0x01
VIRP_APPROVAL_REJECT = 0x02
VIRP_APPROVAL_ESCALATE = 0x03
